# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
